# API 配置
api:
  ernie:
    model: "ernie-speed"
    batch_size: 15
    temperature: 0.1
    top_p: 0.95
  chatgpt:
    model: "gpt-3.5-turbo"
    batch_size: 15
    temperature: 0.1
    max_tokens: 2000

# 性能监控配置
monitoring:
  enabled: true
  log_level: "INFO"
  performance_threshold: 5.0  # 秒

# 数据目录配置
paths:
  input: "data/input"
  output: "data/output"
  analysis: "data/analysis"
  training: "data/training"