# API 配置
api:
  ernie:
    model: "ernie-speed"
    batch_size: 15
    temperature: 0.1
    top_p: 0.95
  chatgpt:
    model: "gpt-3.5-turbo"
    batch_size: 15
    temperature: 0.1
    max_tokens: 2000

# 性能监控配置
monitoring:
  enabled: true
  log_level: "INFO"
  performance_threshold: 5.0  # 秒

# 数据目录配置
paths:
  input: "data/input"
  output: "data/output"
  analysis: "data/analysis"
  training: "data/training"

# 转换器配置
converter:
  # 领域分类配置
  domains:
    技术:
      keywords:
        - 编程
        - 开发
        - python
        - java
        - javascript
        - github
        - 代码
        - 框架
        - 数据库
        - 运维
        - 部署
      domains:
        - github.com
        - stackoverflow.com
        - leetcode.com
        - developer.
        - docs.
        - .dev
    游戏娱乐:
      keywords:
        - 游戏
        - 攻略
        - 娱乐
        - 动漫
        - 直播
        - steam
        - ps5
        - xbox
        - switch
        - moba
        - rpg
      domains:
        - miyoushe.com
        - steam.com
        - xbox.com
        - nintendo.com
        - playstation.com
        - bilibili.com
    媒体资讯:
      keywords:
        - 新闻
        - 资讯
        - 博客
        - 专栏
        - 评论
        - 观点
        - 报道
        - 杂志
        - 媒体
      domains:
        - zhihu.com
        - jianshu.com
        - csdn.net
        - medium.com
        - juejin.cn
        - weixin.qq.com

  # 内容形式配置
  content_types:
    官方文档:
      - docs
      - document
      - 文档
      - 手册
      - 指南
      - reference
    教程指南:
      - tutorial
      - guide
      - 教程
      - 指南
      - 入门
      - 课程
    工具应用:
      - tool
      - app
      - 工具
      - 应用
      - 软件
      - 插件
    社区讨论:
      - forum
      - community
      - 社区
      - 讨论
      - 问答
      - 交流
    博客文章:
      - blog
      - article
      - 博客
      - 文章
      - 专栏
      - post
    视频内容:
      - video
      - 视频
      - 直播
      - live
      - 课程
      - 教学
    资源素材:
      - resource
      - material
      - 资源
      - 素材
      - 模板
      - 源码

  # 特征提取配置
  feature_extraction:
    max_path_keywords: 5
    min_keyword_length: 2
    max_text_length: 1000
    prefixes:
      - doc
      - tip
      - res
      - entry
    domain_features: true
    path_features: true
    combine_features: true
    
  # 数据平衡配置
  data_balance:
    min_samples: 15
    augmentation:
      noise_levels:
        low: 0.1
        medium: 0.2
      max_augmented: 30
      
  # 输出格式配置
  output_format:
    label_prefix: "__label__"
    feature_separator: " "

  # 文本清理配置
  text_cleaning:
    remove_html_tags: true
    remove_urls: false
    remove_numbers: false
    remove_punctuation: true
    lowercase: true
    min_word_length: 2
    max_text_length: 1000

  # 路径处理配置
  path_processing:
    max_segments: 5
    min_segment_length: 2
    ignore_extensions:
      - html
      - php
      - aspx
      - jsp
      - htm
    ignore_segments:
      - www
      - com
      - cn
      - org
      - net

# 模型配置
model:
  fasttext:
    # 训练参数
    learning_rate: 0.05  # 降低学习率
    epochs: 100         # 增加训练轮数
    word_ngrams: 3     # 增加 n-gram 范围
    embedding_dim: 300  # 增加维度
    min_count: 1       # 保留所有特征
    loss_func: "ova"   # 改用 one-vs-all 损失函数
    
    # 预测参数
    prediction_threshold: 0.3
    top_k: 3
    
    # 评估参数
    metrics:
      - precision
      - recall
      - f1
      - per_label_metrics
      - confusion_matrix
      - error_cases
      - label_correlation
    
    # 词向量配置
    word_vectors:
      enabled: true
      path: "data/pretrained/sgns.wiki.word"  # 预训练词向量路径
      min_similarity: 0.6  # 最小相似度阈值
      max_similar_words: 3  # 每个词最多添加的相似词数